---
title: "Assignment_10"
author: "Megan Willis-Jackson, Claire Wang, Ignacio Lafuente"
date: "4/5/2022"
output: html_document
---

# Load Libraries

```{r, message=F}
options(java.parameters = "-Xmx5G")

library(here)
library(tidyverse)
library(stplanr)
library(r5r)
library(sf)
```

# Load data

```{r, message=F}
skims <- here("existing",
                     "data",
                     "skims.csv") %>%
  read_csv(show_col_types = FALSE) %>%
  select(fromId, 
         toId, 
         n_transit_HBO,
         n_SOV_HBO,
         n_HOV_HBO,
         n_walk_HBO,
         n_bike_HBO,
         n_transit_HBW,
         n_SOV_HBW,
         n_HOV_HBW,
         n_walk_HBW,
         n_bike_HBW,
         n_transit_NHB,
         n_SOV_NHB,
         n_HOV_NHB,
         n_walk_NHB,
         n_bike_NHB,
         routes) %>%
  mutate(fromId = as.character(fromId),
         toId = as.character(toId))
```

# Convert PA matrix to OD matrix

```{r, message=F}
HBO_PA_mat <- skims %>%
  od_to_odmatrix(attrib = "n_transit_HBO", 
                 name_orig = "fromId",
                 name_dest = "toId") 

HBO_PA_mat <- HBO_PA_mat[,row.names(HBO_PA_mat)]

HBO_PA_mat_trans <- t(HBO_PA_mat)

HBO_OD_mat <- (HBO_PA_mat + HBO_PA_mat_trans) / 2

HBO_OD_table <- HBO_OD_mat %>%
  odmatrix_to_od() %>%
  rename(fromId = orig,
         toId = dest) %>%
  left_join(skims) %>%
  select(-n_transit_HBO)

#HBW
HBW_PA_mat <- skims %>%
  od_to_odmatrix(attrib = "n_transit_HBW", 
                 name_orig = "fromId",
                 name_dest = "toId") 

HBW_PA_mat <- HBW_PA_mat[,row.names(HBW_PA_mat)]

HBW_PA_mat_trans <- t(HBW_PA_mat)

HBW_OD_mat <- (HBW_PA_mat + HBW_PA_mat_trans) / 2

HBW_OD_table <- HBW_OD_mat %>%
  odmatrix_to_od() %>%
  rename(fromId = orig,
         toId = dest) %>%
  left_join(skims) %>%
  select(-n_transit_HBW)

#NHB
NHB_PA_mat <- skims %>%
  od_to_odmatrix(attrib = "n_transit_NHB", 
                 name_orig = "fromId",
                 name_dest = "toId") 

NHB_PA_mat <- NHB_PA_mat[,row.names(NHB_PA_mat)]

NHB_PA_mat_trans <- t(NHB_PA_mat)

NHB_OD_mat <- (NHB_PA_mat + NHB_PA_mat_trans) / 2

NHB_OD_table <- NHB_OD_mat %>%
  odmatrix_to_od() %>%
  rename(fromId = orig,
         toId = dest) %>%
  left_join(skims) %>%
  select(-n_transit_NHB)


```

# Count trips using each route

```{r, message=F}
route_trips_HBO <- HBO_OD_table %>%
  filter(flow > 0 & !is.na(routes)) %>%
  mutate(route_1 = str_split_fixed(routes, "\\|", 3)[,1],
         route_2 = str_split_fixed(routes, "\\|", 3)[,2],
         route_3 = str_split_fixed(routes, "\\|", 3)[,3]) %>%
  pivot_longer(cols = c(route_1, route_2, route_3),
               values_to = "route") %>%
  filter(route != "") %>%
  select(route, flow) %>%
  group_by(route) %>%
  summarize(ridership = round(sum(flow)))%>%
  mutate(ridership_HBO=ridership)

route_trips_HBW <- HBW_OD_table %>%
  filter(flow > 0 & !is.na(routes)) %>%
  mutate(route_1 = str_split_fixed(routes, "\\|", 3)[,1],
         route_2 = str_split_fixed(routes, "\\|", 3)[,2],
         route_3 = str_split_fixed(routes, "\\|", 3)[,3]) %>%
  pivot_longer(cols = c(route_1, route_2, route_3),
               values_to = "route") %>%
  filter(route != "") %>%
  select(route, flow) %>%
  group_by(route) %>%
  summarize(ridership = round(sum(flow)))%>%
  mutate(ridership_HBW=ridership)

route_trips_NHB <- NHB_OD_table %>%
  filter(flow > 0 & !is.na(routes)) %>%
  mutate(route_1 = str_split_fixed(routes, "\\|", 3)[,1],
         route_2 = str_split_fixed(routes, "\\|", 3)[,2],
         route_3 = str_split_fixed(routes, "\\|", 3)[,3]) %>%
  pivot_longer(cols = c(route_1, route_2, route_3),
               values_to = "route") %>%
  filter(route != "") %>%
  select(route, flow) %>%
  group_by(route) %>%
  summarize(ridership = round(sum(flow)))%>%
  mutate(ridership_NHB=ridership)

#join all table and sum 
route_trip_by_purpose<-left_join(route_trips_HBO,route_trips_HBW,by="route")
route_trip_by_purpose<-left_join(route_trip_by_purpose,route_trips_NHB,by="route")%>%
                        select(route,ridership_HBO,ridership_HBW,ridership_NHB)%>%
                        mutate(sum_ridership=ridership_HBO+ridership_HBW+ridership_NHB)
                        

write_csv(route_trip_by_purpose, here("existing",
              "data",
              "transit_route_trip_by_purpose.csv"))

write_csv(route_trips_NHB, here("existing",
              "data",
              "route_trips_NHB.csv"))

write_csv(route_trips_HBW, here("existing",
              "data",
              "route_trips_HBW.csv"))

write_csv(route_trips_HBO, here("existing",
              "data",
              "route_trips_HBO.csv"))

```

# Graphs on ridership

```{r}
# Stacked (by purpose) histogram for transit lines (number of lines for each ridership bracket)

hist_y <- pivot_longer(select(
  route_trip_by_purpose, -sum_ridership),
  c(ridership_HBO,
    ridership_HBW,
    ridership_NHB),
  names_to = 'purpose') %>%
  ggplot() +
  geom_histogram(aes(x=value, fill=purpose), boundary = 0, bins=20) +
  labs(y = "Count of lines", x = "Trips") +
  theme_bw()

hist_y

ggsave("graphics/A10_transit_lines_hist_ex.png")
```

# Calculate trip distances

```{r, message=F}
centroids <- here("zones",
                   "centroids.geojson")  %>%
  st_read()  %>%
  filter(!st_is_empty(.)) 

origins <- st_as_sf(centroids) %>%
  slice(rep(1:n(), each = n())) %>% 
  mutate(dest_order = 
           rep(seq(1:length(centroids$id)),
               length(centroids$id)))

destinations <- origins %>%
  arrange(dest_order)

#Load R-Objects instead of calculating distances

ped_dist <- readRDS(here("existing",
                         "data",
                         "ped_dist.Rds"))

drive_dist <- readRDS(here("existing",
                         "data",
                         "drive_dist.Rds"))

bike_dist <- readRDS(here("existing",
                         "data",
                         "bike_dist.Rds"))

# r5r_core_existing <- here("existing",
#                           "networks") %>%
#   setup_r5(verbose = FALSE)

# ped_dist <- detailed_itineraries(r5r_core_existing,
#                                  origins = origins,
#                                  destinations = destinations,
#                                  mode = "WALK",
#                                  verbose = FALSE)  %>%
#   mutate(miles = distance / 1609.34) %>%
#   select(fromId, toId, miles) %>%
#   st_drop_geometry()
# 
# saveRDS(ped_dist, here("existing",
#                        "data",
#                        "ped_dist.Rds"))

# drive_dist <- detailed_itineraries(r5r_core_existing,
#                                  origins = origins,
#                                  destinations = destinations,
#                                  mode = "CAR",
#                                  verbose = FALSE) %>%
#   mutate(miles = distance / 1609.34) %>%
#   select(fromId, toId, miles) %>%
#   st_drop_geometry()
# 
# saveRDS(drive_dist, here("existing",
#                        "data",
#                        "drive_dist.Rds"))

# bike_dist <- detailed_itineraries(r5r_core_existing,
#                                  origins = origins,
#                                  destinations = destinations,
#                                  mode = "BICYCLE",
#                                  verbose = FALSE) %>%
#   mutate(miles = distance / 1609.34) %>%
#   select(fromId, toId, miles) %>%
#   st_drop_geometry()
# 
# saveRDS(bike_dist, here("existing",
#                        "data",
#                        "bike_dist.Rds"))
# 
# stop_r5() 
```

# Calculate PMT by mode

```{r, message=F}

PMT_car_HBO <- skims %>%
  left_join(drive_dist, by = c("fromId", "toId")) %>%
  select(n_SOV_HBO, n_HOV_HBO, miles) %>%
  mutate(PMT_SOV_HBO = n_SOV_HBO * miles,
         PMT_HOV_HBO = n_HOV_HBO * miles) %>%
  group_by()%>%
  summarize(total_SOV_miles = sum(PMT_SOV_HBO, na.rm = TRUE),
            total_HOV_miles = sum(PMT_HOV_HBO, na.rm = TRUE))


PMT_bike_HBO<- skims %>%
  left_join(bike_dist, by = c("fromId", "toId")) %>%
  select(n_bike_HBO, miles) %>%
  mutate(PMT_BIKE_HBO = n_bike_HBO * miles) %>%
  summarize(total_bike_miles = sum(PMT_BIKE_HBO, na.rm = TRUE))

PMT_walk_HBO<- skims %>%
  left_join(ped_dist, by = c("fromId", "toId")) %>%
  select(n_walk_HBO, miles) %>%
  mutate(PMT_WALK_HBO = n_walk_HBO * miles) %>%
  summarize(total_WALK_miles = sum(PMT_WALK_HBO, na.rm = TRUE))

PMT_car_HBW <- skims %>%
  left_join(drive_dist, by = c("fromId", "toId")) %>%
  select(n_SOV_HBW, n_HOV_HBW, miles) %>%
  mutate(PMT_SOV_HBW = n_SOV_HBW * miles,
         PMT_HOV_HBW = n_HOV_HBW * miles) %>%
  summarize(total_SOV_miles = sum(PMT_SOV_HBW, na.rm = TRUE),
            total_HOV_miles = sum(PMT_HOV_HBW, na.rm = TRUE))

PMT_bike_HBW<- skims %>%
  left_join(bike_dist, by = c("fromId", "toId")) %>%
  select(n_bike_HBW, miles) %>%
  mutate(PMT_BIKE_HBW = n_bike_HBW * miles) %>%
  summarize(total_bike_miles = sum(PMT_BIKE_HBW, na.rm = TRUE))

PMT_walk_HBW<- skims %>%
  left_join(ped_dist, by = c("fromId", "toId")) %>%
  select(n_walk_HBW, miles) %>%
  mutate(PMT_WALK_HBW = n_walk_HBW * miles) %>%
  summarize(total_WALK_miles = sum(PMT_WALK_HBW, na.rm = TRUE))

PMT_car_NHB <- skims %>%
  left_join(drive_dist, by = c("fromId", "toId")) %>%
  select(n_SOV_NHB, n_HOV_NHB, miles) %>%
  mutate(PMT_SOV_NHB = n_SOV_NHB * miles,
         PMT_HOV_NHB = n_HOV_NHB * miles) %>%
  summarize(total_SOV_miles = sum(PMT_SOV_NHB, na.rm = TRUE),
            total_HOV_miles = sum(PMT_HOV_NHB, na.rm = TRUE))

PMT_bike_NHB<- skims %>%
  left_join(bike_dist, by = c("fromId", "toId")) %>%
  select(n_bike_NHB, miles) %>%
  mutate(PMT_BIKE_NHB = n_bike_NHB * miles) %>%
  summarize(total_bike_miles = sum(PMT_BIKE_NHB, na.rm = TRUE))

PMT_walk_NHB<- skims %>%
  left_join(ped_dist, by = c("fromId", "toId")) %>%
  select(n_walk_NHB, miles) %>%
  mutate(PMT_WALK_NHB = n_walk_NHB * miles) %>%
  summarize(total_WALK_miles = sum(PMT_WALK_NHB, na.rm = TRUE ))


PMT_car_HBO
PMT_bike_HBO
PMT_walk_HBO
PMT_car_HBW
PMT_bike_HBW
PMT_walk_HBW
PMT_car_NHB
PMT_bike_NHB
PMT_walk_NHB


PMT_car <- rbind(PMT_car_HBO,PMT_car_HBW,PMT_car_NHB) %>% 
  mutate(total_car_miles=total_SOV_miles+total_HOV_miles, purpose = c('HBO', 'HBW', 'NHB')) %>% 
  select(total_car_miles, purpose)
  
PMT_bike <-rbind(PMT_bike_HBO,PMT_bike_HBW,PMT_bike_NHB)
PMT_walk <-rbind(PMT_walk_HBO,PMT_walk_HBW,PMT_walk_NHB)

PMT_car
PMT_bike
PMT_walk

write_csv(skims, here("existing",
              "data",
              "skims.csv"))

write_csv(PMT_car, here("existing",
              "data",
              "PMT_car.csv"))

write_csv(PMT_bike, here("existing",
              "data",
              "PMT_bike.csv"))

write_csv(PMT_walk, here("existing",
              "data",
              "PMT_walk.csv"))

```

#Calculate VMT
```{r}
VMT <- mutate(PMT_car, multipliers = c(2.71, 2.42, 2.75)) %>% 
  mutate(total_car_miles = total_car_miles / multipliers)
  

VMT

```

# Alternative conditions

# Load data

```{r, message=F}
skims_alt <- here("alternative",
                     "data",
                     "skims_alt.csv") %>%
  read_csv(show_col_types = FALSE) %>%
  select(fromId, 
         toId, 
         n_transit_HBO,
         n_SOV_HBO,
         n_HOV_HBO,
         n_walk_HBO,
         n_bike_HBO,
         n_transit_HBW,
         n_SOV_HBW,
         n_HOV_HBW,
         n_walk_HBW,
         n_bike_HBW,
         n_transit_NHB,
         n_SOV_NHB,
         n_HOV_NHB,
         n_walk_NHB,
         n_bike_NHB,
         routes) %>%
  mutate(fromId = as.character(fromId),
         toId = as.character(toId))
```

# Convert PA matrix to OD matrix

```{r, message=F}
HBO_PA_mat_alt <- skims_alt %>%
  od_to_odmatrix(attrib = "n_transit_HBO", 
                 name_orig = "fromId",
                 name_dest = "toId") 

HBO_PA_mat_alt <- HBO_PA_mat_alt[,row.names(HBO_PA_mat_alt)]

HBO_PA_mat_trans_alt <- t(HBO_PA_mat_alt)

HBO_OD_mat_alt <- (HBO_PA_mat_alt + HBO_PA_mat_trans_alt) / 2

HBO_OD_table_alt <- HBO_OD_mat_alt %>%
  odmatrix_to_od() %>%
  rename(fromId = orig,
         toId = dest) %>%
  left_join(skims_alt) %>%
  select(-n_transit_HBO)

#HBW
HBW_PA_mat_alt <- skims_alt %>%
  od_to_odmatrix(attrib = "n_transit_HBW", 
                 name_orig = "fromId",
                 name_dest = "toId") 

HBW_PA_mat_alt <- HBW_PA_mat_alt[,row.names(HBW_PA_mat_alt)]

HBW_PA_mat_trans_alt <- t(HBW_PA_mat_alt)

HBW_OD_mat_alt <- (HBW_PA_mat_alt + HBW_PA_mat_trans_alt) / 2

HBW_OD_table_alt <- HBW_OD_mat_alt %>%
  odmatrix_to_od() %>%
  rename(fromId = orig,
         toId = dest) %>%
  left_join(skims_alt) %>%
  select(-n_transit_HBW)

#NHB
NHB_PA_mat_alt <- skims_alt %>%
  od_to_odmatrix(attrib = "n_transit_NHB", 
                 name_orig = "fromId",
                 name_dest = "toId") 

NHB_PA_mat_alt <- NHB_PA_mat_alt[,row.names(NHB_PA_mat_alt)]

NHB_PA_mat_trans_alt <- t(NHB_PA_mat_alt)

NHB_OD_mat_alt <- (NHB_PA_mat_alt + NHB_PA_mat_trans_alt) / 2

NHB_OD_table_alt <- NHB_OD_mat_alt %>%
  odmatrix_to_od() %>%
  rename(fromId = orig,
         toId = dest) %>%
  left_join(skims_alt) %>%
  select(-n_transit_NHB)


```

# Count trips using each route

```{r, message=F}
route_trips_HBO_alt <- HBO_OD_table_alt %>%
  filter(flow > 0 & !is.na(routes)) %>%
  mutate(route_1 = str_split_fixed(routes, "\\|", 3)[,1],
         route_2 = str_split_fixed(routes, "\\|", 3)[,2],
         route_3 = str_split_fixed(routes, "\\|", 3)[,3]) %>%
  pivot_longer(cols = c(route_1, route_2, route_3),
               values_to = "route") %>%
  filter(route != "") %>%
  select(route, flow) %>%
  group_by(route) %>%
  summarize(ridership = round(sum(flow)))%>%
  mutate(ridership_HBO=ridership)

route_trips_HBW_alt <- HBW_OD_table_alt %>%
  filter(flow > 0 & !is.na(routes)) %>%
  mutate(route_1 = str_split_fixed(routes, "\\|", 3)[,1],
         route_2 = str_split_fixed(routes, "\\|", 3)[,2],
         route_3 = str_split_fixed(routes, "\\|", 3)[,3]) %>%
  pivot_longer(cols = c(route_1, route_2, route_3),
               values_to = "route") %>%
  filter(route != "") %>%
  select(route, flow) %>%
  group_by(route) %>%
  summarize(ridership = round(sum(flow)))%>%
  mutate(ridership_HBW=ridership)

route_trips_NHB_alt <- NHB_OD_table_alt %>%
  filter(flow > 0 & !is.na(routes)) %>%
  mutate(route_1 = str_split_fixed(routes, "\\|", 3)[,1],
         route_2 = str_split_fixed(routes, "\\|", 3)[,2],
         route_3 = str_split_fixed(routes, "\\|", 3)[,3]) %>%
  pivot_longer(cols = c(route_1, route_2, route_3),
               values_to = "route") %>%
  filter(route != "") %>%
  select(route, flow) %>%
  group_by(route) %>%
  summarize(ridership = round(sum(flow)))%>%
  mutate(ridership_NHB=ridership)

#join all table and sum 
route_trip_by_purpose_alt<-left_join(route_trips_HBO_alt,route_trips_HBW_alt,by="route") %>%
  left_join(route_trips_NHB_alt,by="route")%>%
                        select(route,ridership_HBO,ridership_HBW,ridership_NHB)%>%
                        mutate(sum_ridership=ridership_HBO+ridership_HBW+ridership_NHB)
                        

write_csv(route_trip_by_purpose_alt, here("alternative",
              "data",
              "transit_route_trip_by_purpose_alt.csv"))

write_csv(route_trips_NHB_alt, here("alternative",
              "data",
              "route_trips_NHB_alt.csv"))

write_csv(route_trips_HBW_alt, here("alternative",
              "data",
              "route_trips_HBW_alt.csv"))

write_csv(route_trips_HBO_alt, here("alternative",
              "data",
              "route_trips_HBO_alt.csv"))

```

# Graphs on ridership

```{r}
# Stacked (by purpose) histogram for transit lines (number of lines for each ridership bracket)

hist_y_alt <- pivot_longer(select(
  route_trip_by_purpose_alt, -sum_ridership),
  c(ridership_HBO,
    ridership_HBW,
    ridership_NHB),
  names_to = 'purpose') %>%
  ggplot() +
  geom_histogram(aes(x=value, fill=purpose), boundary = 0, bins=20) +
  labs(y = "Count of lines", x = "Trips - alt") +
  theme_bw()

hist_y_alt

ggsave("graphics/A10_transit_lines_hist_alt.png")

# Table showing the 'top line' for each purpose and overall

top_ridership_line <- data.frame(
  mode = c('HBO', 'HBW', 'NHB'),
  existing = c(
    route_trip_by_purpose[route_trip_by_purpose[which.max(route_trip_by_purpose$HBO_ridership),]],
    route_trip_by_purpose[route_trip_by_purpose[which.max(route_trip_by_purpose$HBW_ridership),]],
    route_trip_by_purpose[route_trip_by_purpose[which.max(route_trip_by_purpose$NHB_ridership),]]
              ),
  alternative = c(
    route_trip_by_purpose_alt[route_trip_by_purpose_alt[which.max(route_trip_by_purpose$HBO_ridership),]],
    route_trip_by_purpose_alt[route_trip_by_purpose_alt[which.max(route_trip_by_purpose_alt$HBW_ridership),]],
    route_trip_by_purpose_alt[route_trip_by_purpose_alt[which.max(route_trip_by_purpose_alt$NHB_ridership),]]
  ))

top_ridership_line
```

# Calculate PMT by mode

```{r, message=F}

PMT_car_HBO_alt <- skims_alt %>%
  left_join(drive_dist, by = c("fromId", "toId")) %>%
  select(n_SOV_HBO, n_HOV_HBO, miles) %>%
  mutate(PMT_SOV_HBO = n_SOV_HBO * miles,
         PMT_HOV_HBO = n_HOV_HBO * miles) %>%
  group_by()%>%
  summarize(total_SOV_miles = sum(PMT_SOV_HBO, na.rm = TRUE),
            total_HOV_miles = sum(PMT_HOV_HBO, na.rm = TRUE))


PMT_bike_HBO_alt <- skims_alt %>%
  left_join(bike_dist, by = c("fromId", "toId")) %>%
  select(n_bike_HBO, miles) %>%
  mutate(PMT_BIKE_HBO = n_bike_HBO * miles) %>%
  summarize(total_bike_miles = sum(PMT_BIKE_HBO, na.rm = TRUE))

PMT_walk_HBO_alt <- skims_alt %>%
  left_join(ped_dist, by = c("fromId", "toId")) %>%
  select(n_walk_HBO, miles) %>%
  mutate(PMT_WALK_HBO = n_walk_HBO * miles) %>%
  summarize(total_WALK_miles = sum(PMT_WALK_HBO, na.rm = TRUE))

PMT_car_HBW_alt <- skims_alt %>%
  left_join(drive_dist, by = c("fromId", "toId")) %>%
  select(n_SOV_HBW, n_HOV_HBW, miles) %>%
  mutate(PMT_SOV_HBW = n_SOV_HBW * miles,
         PMT_HOV_HBW = n_HOV_HBW * miles) %>%
  summarize(total_SOV_miles = sum(PMT_SOV_HBW, na.rm = TRUE),
            total_HOV_miles = sum(PMT_HOV_HBW, na.rm = TRUE))

PMT_bike_HBW_alt <- skims_alt %>%
  left_join(bike_dist, by = c("fromId", "toId")) %>%
  select(n_bike_HBW, miles) %>%
  mutate(PMT_BIKE_HBW = n_bike_HBW * miles) %>%
  summarize(total_bike_miles = sum(PMT_BIKE_HBW, na.rm = TRUE))

PMT_walk_HBW_alt <- skims_alt %>%
  left_join(ped_dist, by = c("fromId", "toId")) %>%
  select(n_walk_HBW, miles) %>%
  mutate(PMT_WALK_HBW = n_walk_HBW * miles) %>%
  summarize(total_WALK_miles = sum(PMT_WALK_HBW, na.rm = TRUE))

PMT_car_NHB_alt <- skims_alt %>%
  left_join(drive_dist, by = c("fromId", "toId")) %>%
  select(n_SOV_NHB, n_HOV_NHB, miles) %>%
  mutate(PMT_SOV_NHB = n_SOV_NHB * miles,
         PMT_HOV_NHB = n_HOV_NHB * miles) %>%
  summarize(total_SOV_miles = sum(PMT_SOV_NHB, na.rm = TRUE),
            total_HOV_miles = sum(PMT_HOV_NHB, na.rm = TRUE))

PMT_bike_NHB_alt <- skims_alt %>%
  left_join(bike_dist, by = c("fromId", "toId")) %>%
  select(n_bike_NHB, miles) %>%
  mutate(PMT_BIKE_NHB = n_bike_NHB * miles) %>%
  summarize(total_bike_miles = sum(PMT_BIKE_NHB, na.rm = TRUE))

PMT_walk_NHB_alt <- skims_alt %>%
  left_join(ped_dist, by = c("fromId", "toId")) %>%
  select(n_walk_NHB, miles) %>%
  mutate(PMT_WALK_NHB = n_walk_NHB * miles) %>%
  summarize(total_WALK_miles = sum(PMT_WALK_NHB, na.rm = TRUE ))


PMT_car_HBO_alt
PMT_bike_HBO_alt
PMT_walk_HBO_alt
PMT_car_HBW_alt
PMT_bike_HBW_alt
PMT_walk_HBW_alt
PMT_car_NHB_alt
PMT_bike_NHB_alt
PMT_walk_NHB_alt


PMT_car_alt <- rbind(
  PMT_car_HBO_alt,
  PMT_car_HBW_alt,
  PMT_car_NHB_alt) %>% 
  mutate(total_car_miles=total_SOV_miles+total_HOV_miles, purpose = c('HBO', 'HBW', 'NHB')) %>% 
  select(total_car_miles, purpose)
  
PMT_bike_alt <-rbind(PMT_bike_HBO_alt,PMT_bike_HBW_alt,PMT_bike_NHB_alt)
PMT_walk_alt <-rbind(PMT_walk_HBO_alt,PMT_walk_HBW_alt,PMT_walk_NHB_alt)

PMT_car_alt
PMT_bike_alt
PMT_walk_alt

write_csv(skims_alt, here("alternative",
              "data",
              "skims_10_alt.csv"))

write_csv(PMT_car_alt, here("alternative",
              "data",
              "PMT_car_alt.csv"))

write_csv(PMT_bike_alt, here("alternative",
              "data",
              "PMT_bike_alt.csv"))

write_csv(PMT_walk_alt, here("alternative",
              "data",
              "PMT_walk_alt.csv"))


```

#Calculate VMT
```{r}
VMT_alt <- mutate(PMT_car_alt, multipliers = c(2.71, 2.42, 2.75)) %>% 
  mutate(total_car_miles = total_car_miles / multipliers)
  
VMT_alt

```

# Bar chart for comparing VMT and PMT

```{r}
# barplot with two bars, existing and alternative VMT and PMT

purpose <- c('HBO', 'HBW', 'NHB')

VMT_PMT_existing <- data.frame(
  VMT = c(VMT$total_car_miles),
  PMT_walk = c(PMT_walk$total_WALK_miles),
  PMT_bike = c(PMT_bike$total_bike_miles)) %>% 
  transpose()
colnames(VMT_PMT_existing) <- purpose

VMT_PMT_alternative <- data.frame(
  VMT = c(VMT_alt$total_car_miles),
  PMT_walk_alt = c(PMT_walk_alt$total_WALK_miles),
  PMT_bike_alt = c(PMT_bike_alt$total_bike_miles)) %>% 
  t()
colnames(VMT_PMT_alternative) <- purpose

VMT_PMT_growth <- VMT_PMT_alternative / VMT_PMT_existing - 1 %>% 
  mutate(totals = HBO + HBW + NHB)

VMT_PMT_growth_chart <- ggplot(VMT_PMT_growth,
                               aes(x = 'ID',
                                   y = value,
                                   fill = purpose)) +
  geom_bar(stat="identity")

VMT_PMT_growth_chart

ggsave("graphics/A10_vmt_pmt_diff.png")
```

