---
title: "Assignment02"
author: "Megan Willis-Jackson"
date: "2/3/2022"
output: html_document
---

```{r libraries, echo=F, message=F, warning=F}
library(tidyverse)
library(tidycensus)
library(ggplot2)
library(sf)
library(units)
library(tigris)


```

# Load Variables

```{r}
sanjose_msa <- core_based_statistical_areas() %>%
  filter(GEOID == "41940")

view(load_variables(2019, "acs5"))

vars <- c(med_income = "B06011_001") #discuss which variables are needed for analysis

census <- get_acs(geography = "tract",
                  state = "CA",
                  variables = vars,
                  output = "wide",
                  geometry = T) %>%
  st_filter(sanjose_msa)


ggplot(census) +
  geom_sf(aes(fill = med_incomeE), color = alpha("white", .1)) +
  theme_void()

#download employment data
#NOTE: I think we also will need the LEHD residence area characteristics,
#to determine which RESIDENTS will no longer have to commute, in addition to 
#which jobs in the MSA will no longer have commuters.

#creates new variables, including a WFH variable which
#assumes that the job is able to be at least partially remote.
lehd_blocks_jobs <- read_csv("https://lehd.ces.census.gov/data/lodes/LODES7/ca/wac/ca_wac_S000_JT00_2019.csv.gz", 
                             show_col_types = F) %>%
  rename(total_jobs = C000) %>%
  mutate(basic_jobs = CNS01+CNS02+CNS03+CNS04+CNS05+CNS06+CNS08+CNS09) %>%
  rename(retail_jobs = CNS07) %>%
  mutate(service_jobs = total_jobs - basic_jobs - retail_jobs,
         WFH_jobs = CNS09+CNS10+CNS12+CNS13+CNS19+CNS20) %>%
  select(w_geocode, total_jobs, basic_jobs, retail_jobs, service_jobs, WFH_jobs)

#load the residence area characteristics
lehd_blocks_emp <- read_csv("https://lehd.ces.census.gov/data/lodes/LODES7/ca/rac/ca_rac_S000_JT00_2019.csv.gz",
                            show_col_types = F) %>%
  rename(total_emp = C000) %>%
  mutate(basic_emp = CNS01+CNS02+CNS03+CNS04+CNS05+CNS06+CNS08+CNS09) %>%
  rename(retail_emp = CNS07) %>%
  mutate(service_emp = total_emp - basic_emp - retail_emp,
         WFH_emp = CNS09+CNS10+CNS12+CNS13+CNS19+CNS20) %>%
  select(h_geocode, total_emp, basic_emp, retail_emp, service_emp, WFH_emp)


#collapse lehd variables to census tracts
lehd_tracts_jobs <- lehd_blocks_jobs %>%
  mutate(w_geocode = as.character(w_geocode)) %>%
  mutate(GEOID = substr(w_geocode, 1, 11)) %>%
  select(-w_geocode) %>%
  group_by(GEOID) %>%
  summarise(across(everything(), ~sum(.))) 

lehd_tracts_emp <- lehd_blocks_emp %>%
  mutate(h_geocode = as.character(h_geocode)) %>%
  mutate(GEOID = substr(h_geocode, 1, 11)) %>%
  select(-h_geocode) %>%
  group_by(GEOID) %>%
  summarise(across(everything(), ~sum(.))) 

census <- census %>%
  left_join(lehd_tracts_jobs, by = "GEOID") %>%
  left_join(lehd_tracts_emp, by = "GEOID")



#read in the Origin/Destination LEHD data
od <- read_csv("https://lehd.ces.census.gov/data/lodes/LODES7/ca/od/ca_od_aux_JT00_2019.csv.gz",
               show_col_types = F) %>%
  mutate(w_geocode = as.character(w_geocode),
         h_geocode = as.character(h_geocode)) %>%
  mutate(w_GEOID = substr(w_geocode, 1, 11),
         h_GEOID = substr(h_geocode, 1, 11)) %>%
  select(-h_geocode, -w_geocode) %>%
  group_by(w_GEOID, h_GEOID) %>%
  summarise(total = sum(S000),
            goodsproducing = sum(SI01),
            trade_transpo_utility = sum(SI02),
            otherservices = sum(SI03)) %>%
  full_join(census, by = c("w_GEOID" = "GEOID")) %>%
  select(w_GEOID, h_GEOID, total, goodsproducing, 
         trade_transpo_utility, otherservices, NAME) %>%
  mutate(work_tract = ifelse(is.na(NAME) == F, 1, 0)) %>%
  select(-NAME) %>%
  full_join(census, by = c("h_GEOID" = "GEOID")) %>%
  select(w_GEOID, h_GEOID, total, goodsproducing, 
         trade_transpo_utility, otherservices, NAME, work_tract) %>%
  mutate(home_tract = ifelse(is.na(NAME) == F, 1, 0)) %>%
  select(-NAME) %>%
  filter(is.na(w_GEOID) == F,
         is.na(h_GEOID) == F)

#the OD LEHD data does not seem to have any tracts in the "home" designation
#that overlaps with tracts in the San Jose MSA, which seems odd. I went
#back to the raw data and that is the case, though, so I'm not sure what 
#to think.

od %>%
  group_by(work_tract, home_tract) %>%
  summarise(total = sum(total),
            goodsproducing = sum(goodsproducing),
            trade_transpo_utility = sum(trade_transpo_utility),
            other_services = sum(otherservices))

```









