---
title: "assignment 6"
author: "Megan Willis-Jackson, Claire Wang, Ignacio Lafuente"
date: "3/3/2022"
output: html_document
---

```{r, message=F, echo=F, warning=F}
library(r5r)
library(here)
library(tidyverse)
library(sf)
library(lubridate)
library(modelr)
library(jtools)
```

#set up data
```{r, message=F, echo=F, warning=F}
access <- here("existing",
               "data",
               "access_compare.csv") %>%
  read_csv()

zones <- here("existing",
               "data",
               "existing_sanjose.csv") %>%
  read_csv() %>%
  mutate(inc_quint_1 = inc_lt_10kE +
                       inc_btw_10k_15kE +
                       inc_btw_15k_20kE +
                       inc_btw_20k_25kE,
         inc_quint_5 = inc_btw_100k_125kE +
                       inc_btw_125k_150kE +
                       inc_btw_150k_200kE +
                       inc_gt_200kE)
```

#select model variables
```{r, echo=FALSE}
model_data <- left_join(zones, access) %>%
  mutate(pct_big_hh = (hh_3personE + hh_4person_plusE) / total_hhsE,
         pct_lo_inc = inc_quint_1 / total_hhsE,
         pct_hi_inc = inc_quint_5 / total_hhsE,
         pct_no_veh = no_veh_hhE / total_hhsE,
         pct_wfh_pop=total_wfhE/total_workerE,
         pct_cardef_hh = cardef_hh / total_hhsE,
         transit_access_100k = transit_access/100000) %>%
  select(GEOID, pct_big_hh, pct_lo_inc, 
         pct_hi_inc, ratio, pct_no_veh,pct_wfh_pop, pct_cardef_hh, car_access, 
         transit_access_100k)

model_data <- model_data %>% 
    mutate(ratio=ifelse(model_data$ratio > 1, 1, model_data$ratio))

```

#visualize model variables, exploring correlations
```{r}
scatterplot_yy <- ggplot(model_data, aes(y = pct_no_veh, x = pct_cardef_hh)) +
  geom_point(size = 1, color = "blue") +
  geom_smooth(size = 0.5, lty = "dashed", color = "red", method = "lm") # corr between both Ys

# corr between "Y1" (carless) and all Xs

scatterplot_y1x1 <- ggplot(model_data, aes(y = pct_no_veh, x = pct_big_hh)) +
  geom_point(size = 1, color = "blue") +
  geom_smooth(size = 0.5, lty = "dashed", color = "blue", method = "lm")

scatterplot_y1x2 <- ggplot(model_data, aes(y = pct_no_veh, x = pct_lo_inc)) +
  geom_point(size = 1, color = "blue") +
  geom_smooth(size = 0.5, lty = "dashed", color = "blue", method = "lm")

scatterplot_y1x3 <- ggplot(model_data, aes(y = pct_no_veh, x = pct_hi_inc)) +
  geom_point(size = 1, color = "blue") +
  geom_smooth(size = 0.5, lty = "dashed", color = "blue", method = "lm")

scatterplot_y1x4 <- ggplot(model_data, aes(y = pct_no_veh, x = ratio)) +
  geom_point(size = 1, color = "blue") +
  geom_smooth(size = 0.5, lty = "dashed", color = "blue", method = "lm")

scatterplot_y1x5 <- ggplot(model_data, aes(y = pct_no_veh, x = pct_wfh_pop)) +
  geom_point(size = 1, color = "blue") +
  geom_smooth(size = 0.5, lty = "dashed", color = "blue", method = "lm")

scatterplot_y1x6 <- ggplot(model_data, aes(y = pct_no_veh, x = car_access)) +
  geom_point(size = 1, color = "blue") +
  geom_smooth(size = 0.5, lty = "dashed", color = "blue", method = "lm")

scatterplot_y1x7 <- ggplot(model_data, aes(y = pct_no_veh, x = transit_access_100k)) +
  geom_point(size = 1, color = "blue") +
  geom_smooth(size = 0.5, lty = "dashed", color = "blue", method = "lm")

# corr between "Y2" (auto_deficit) and all Xs

scatterplot_y2x1 <- ggplot(model_data, aes(y = pct_cardef_hh, x = pct_big_hh)) +
  geom_point(size = 1, color = "blue") +
  geom_smooth(size = 0.5, lty = "dashed", color = "green", method = "lm")

scatterplot_y2x2 <- ggplot(model_data, aes(y = pct_cardef_hh, x = pct_lo_inc)) +
  geom_point(size = 1, color = "blue") +
  geom_smooth(size = 0.5, lty = "dashed", color = "green", method = "lm")

scatterplot_y2x3 <- ggplot(model_data, aes(y = pct_cardef_hh, x = pct_hi_inc)) +
  geom_point(size = 1, color = "blue") +
  geom_smooth(size = 0.5, lty = "dashed", color = "green", method = "lm")

scatterplot_y2x4 <- ggplot(model_data, aes(y = pct_cardef_hh, x = ratio)) +
  geom_point(size = 1, color = "blue") +
  geom_smooth(size = 0.5, lty = "dashed", color = "green", method = "lm")

scatterplot_y2x5 <- ggplot(model_data, aes(y = pct_cardef_hh, x = pct_wfh_pop)) +
  geom_point(size = 1, color = "blue") +
  geom_smooth(size = 0.5, lty = "dashed", color = "green", method = "lm")

scatterplot_y2x6 <- ggplot(model_data, aes(y = pct_cardef_hh, x = car_access)) +
  geom_point(size = 1, color = "blue") +
  geom_smooth(size = 0.5, lty = "dashed", color = "green", method = "lm")

scatterplot_y2x7 <- ggplot(model_data, aes(y = pct_cardef_hh, x = transit_access_100k)) +
  geom_point(size = 1, color = "blue") +
  geom_smooth(size = 0.5, lty = "dashed", color = "green", method = "lm")

scatterplot_yy
scatterplot_y1x1
scatterplot_y1x2
scatterplot_y1x3
scatterplot_y1x4
scatterplot_y1x5
scatterplot_y1x6
scatterplot_y1x7
scatterplot_y2x1
scatterplot_y2x2
scatterplot_y2x3
scatterplot_y2x4
scatterplot_y2x5
scatterplot_y2x6
scatterplot_y2x7
```

#estimate regressions 
```{r, echo=FALSE}
model1 <- lm(pct_no_veh ~  pct_big_hh+pct_lo_inc+ pct_hi_inc+pct_wfh_pop + transit_access_100k, data = model_data)

export_summs(model1)

hist(model_data$car_access)

#Refine model after taking out non-statistically significant variables
model2 <- lm(pct_no_veh ~ pct_lo_inc + ratio, data = model_data)

export_summs(model1, model2)

```


#Apply regression to alternative
```{r, echo=FALSE}
alt_access <- here("alternative",
               "data",
               "access_compare.csv") %>%
  read_csv()

alt_zones <- here("alternative",
               "data",
               "zone_data.csv") %>%
  read_csv() %>%
  left_join(access) %>%
  mutate(pct_big_hh = (hh_3personE + hh_4person_plusE) / total_hhsE,
         pct_lo_inc = inc_quint_1 / total_hhsE,
         pct_hi_inc = inc_quint_5 / total_hhsE,
         pct_no_veh = no_vehE / total_hhsE) %>%
  add_predictions(model = model2) %>%
  mutate(pct_no_veh = pred) %>%
  mutate(no_vehE = round(total_hhsE * pct_no_veh)) 

```

#saving data
```{r}
write_csv(alt_zones, file = here("existing", 
                                      "data",
                                      "alt_zones.csv"))



```
