---
title: "Assignment05"
author: "Megan Willis-Jackson, Claire Wang, Ignacio Lafuente"
date: "2/25/2022"
output: html_document
---

# Load Libraries

```{r, message=F, echo=F, warning=F}
options(java.parameters = '-Xmx5G')

library(r5r)
library(here)
library(tidyverse)
library(sf)
library(lubridate)
```

#set up centroid for existing conditions
```{r, message=F, echo=F, warning=F}
jobs <- here("existing",
             "data",
             "existing_sanjose.csv") %>%
  read_csv() %>%
  select(GEOID, total_jobs) %>%
  mutate(GEOID = as.character(GEOID))%>%
  rename(id = GEOID)

centroids <- here("zones",
                  "centroids.geojson") %>%
  st_read() %>%
  left_join(jobs, by= "id") 
```

#set up r5r core
```{r, message=F, echo=F, warning=F}
existing_core <- here("existing",
                      "networks") %>%
  setup_r5(verbose = FALSE)
```

#calculate driving under existing conditions
```{r, message=F, echo=F, warning=F}
car_access_existing <- accessibility(existing_core,
                                     origins = centroids,
                                     destinations = centroids,
                                     opportunities_colname = 'total_jobs',
                                     mode = "CAR",
                                     decay_function = "logistic", #need to make a decision here
                                     cutoffs = 30,
                                     decay_value = 3, 
                                     verbose = FALSE)
```

#calculate Transit under existing conditions
```{r, message=F, echo=F, warning=F}
transit_access_existing <- accessibility(existing_core,
                                     origins = centroids,
                                     destinations = centroids,
                                     opportunities_colname = 'total_jobs',
                                     mode = "TRANSIT",
                                     decay_function = "logistic",
                                     cutoffs = 30,
                                     decay_value = 3, 
                                     verbose = FALSE,
                                     departure_datetime = 
                                       ymd_hm("2022-02-14 16:00"),
                                     time_window = 120)
```

#compare driving vs transit for existing 
```{r, message=F, echo=F, warning=F}
car_access_existing <- car_access_existing %>%
  select(from_id, accessibility) %>%
  rename(GEOID = from_id,
         car_access = accessibility)

transit_access_existing <- transit_access_existing %>%
  select(from_id, accessibility) %>%
  rename(GEOID = from_id,
         transit_access = accessibility)

access_compare <- left_join(car_access_existing, transit_access_existing) %>%
  mutate(ratio = transit_access / car_access)
```

#create choropleth maps for existing conditions
```{r, message=F, echo=F, warning=F}
# chor_map(access_compare, "ratio", 
#                            title = "Existing #condition comparison for driving and transit")
zones <- here("zones",
             "zones_sanjose.geojson")

# transit_to_car_acc <- ggplot(zones) +
  # geom_sf(aes(fill = transit_existing),
  #         color = NA) +
  # geom_sf(data = zones %>% filter(GEOID == "06085505006"),
  #         fill = "magenta", color = NA) +
  # scale_fill_gradientn(colours = transit_map_palette,
  #                      name = "Travel Time\nto Max Job Tract\nby Transit") +
  # annotation_scale() +
  # theme_void() +
  # theme(text = element_text(size = 14))

opportunities_map <- ggplot(centroids) +
  geom_sf(aes(size = total_jobs),
        fill = "firebrick1",
        alpha = 0.5) +
  theme_void() +
  theme(text = element_text(size = 14)) +
  geom_sf(zones, aes(color = "gray32", size = 1))

hist_ratio <- ggplot(access_compare, aes(x = ratio)) +
  geom_histogram(aes(y=..count..*10), bins = 30, fill = "dodgerblue3") +
  labs(y = "Count of Tracts", x = "Transit accessibility / Car accessibility") +
  theme_minimal()

opportunities_map
hist_ratio

ggsave("graphics/opportunities_map.png", opportunities_map, device = "png")

ggsave("graphics/hist_acc_ratio.png", hist_ratio, device = "png")

```

#saving data
```{r}
write_csv(access_compare, file = here("existing", 
                                      "data",
                                      "access_compare.csv"))

```

