---
title: "assignment 7"
author: "Megan Willis-Jackson, Claire Wang, Ignacio Lafuente"
date: "3/3/2022"
output: html_document
---

```{r, message=F, echo=F, warning=F}
library(here)
library(tidyverse)
library(survey)
library(srvyr)
library(naniar)
library(jtools)
library(knitr)
```


#set up NHTS data
```{r, message=F, echo=F, warning=F}
temp <- tempfile()
download.file("https://nhts.ornl.gov/assets/2016/download/csv.zip", temp)

trips <- read_csv(unz(temp, "trippub.csv"))
person <- read_csv(unz(temp, "perpub.csv"))
hhs <- read_csv(unz(temp, "hhpub.csv"))

unlink(temp)
```


#select household-level variables
```{r, message=F, echo=F, warning=F}
sanjose_hhs <- hhs %>%
  filter(HH_CBSA == "41940") %>%
  mutate(inc_quint_ = case_when(HHFAMINC == "01" ~ "1st",
                               HHFAMINC == "02" ~ "1st",
                               HHFAMINC == "03" ~ "1st",
                               HHFAMINC == "04" ~ "2nd",
                               HHFAMINC == "05" ~ "2nd",
                               HHFAMINC == "06" ~ "3rd",
                               HHFAMINC == "07" ~ "4th",
                               HHFAMINC == "08" ~ "5th",
                               HHFAMINC == "09" ~ "5th",
                               HHFAMINC == "10" ~ "5th",
                               HHFAMINC == "11" ~ "5th",
                               TRUE ~ "NA")) %>%
  mutate(size_ = case_when(HHSIZE == 1 ~ "one",
                              HHSIZE == 2 ~ "two",
                              HHSIZE == 3 ~ "three",
                              TRUE ~ "four_plus")) %>%
  mutate(zero_veh_ = (HHVEHCNT == 0)) %>%
  replace_with_na(list(inc_quint_ = "NA")) %>%
  select(HOUSEID, zero_veh_, size_, inc_quint_, WRKCOUNT, WTHHFIN) # adding no. of workers at the hh

```

#select person-level variables
```{r, message=F, echo=F, warning=F}
# workers who work from home, have the option to do so, or have effectively worked from home more than one day during that month, will be considered.

# the data will be aggregated at the hh level and contrasted with the number of total workers there. The variable will measure how generation of trips is affected as WFH becomes more relevant as a % at the household level.

# extrapolation, althogh imperfect (from disaggregated data to aggregated data), will apply its coefficients to the % of WFH at each zone.

sanjose_pers <- person %>%
  filter(HH_CBSA == "41940") %>%
  mutate(WFH_exh = case_when(WRK_HOME == '01' | WKRMHM == '01' | WKFMHMXX > 0) ~ 1,
         TRUE ~ 0) %>%
  select(HOUSEID, WFH_exh)
```


#select trip-level variables
```{r, message=F, echo=F, warning=F}

# we decided to still count HBW trips for WFH individuals because that is still a possibility from time to time.

# moreover, if our assumptions are correct, this could be measured and prove a smaller generation.

trips_by_purpose <- trips %>% 
  filter(HH_CBSA == "41940") %>%
  select(HOUSEID, WHYFROM, WHYTO) %>%
  mutate(home_based = case_when(WHYTO == "01" ~ TRUE,
                                WHYTO == "02" ~ TRUE,
                                WHYFROM == "01" ~ TRUE,
                                WHYFROM == "02" ~ TRUE,
                                TRUE ~ FALSE)) %>%
  mutate(work = ifelse(WHYTO == "03" | WHYFROM == "03", TRUE, FALSE)) %>%
  mutate(purpose = case_when(home_based & work ~ "HBW",
                            home_based ~ "HBO",
                            TRUE ~ "NHB")) %>%
  group_by(HOUSEID, purpose) %>%
  summarize(n = n()) %>%
  pivot_wider(names_from = "purpose", values_from = "n") 

sanjose_pers_agg <- sanjose_pers %>%
  group_by(HOUSEID, WFH_exh) %>%
  summarize(n = n()) %>%
  pivot_wider(names_from = "purpose", values_from = "n")

# #differentiate wfh household household trips from other home-based trip
# trips_by_purpose_Claire <- trips %>% 
#   filter(HH_CBSA == "41940") %>%
#   select(HOUSEID, WHYFROM, WHYTO) %>%
#   mutate(home_based = case_when(WHYTO == "01" ~ TRUE,
#                                 WHYFROM == "01" ~ TRUE,
#                                 TRUE ~ FALSE)) %>%
#   mutate(work = ifelse(WHYTO == "03" | WHYFROM == "03", TRUE, FALSE)) %>%
#   mutate(wfh = ifelse(WHYTO == "02" | WHYFROM == "02", TRUE, FALSE)) %>%
#   mutate(purpose = case_when(home_based & work ~ "HBW",
#                             home_based ~ "HBO",
#                             wfh ~ "WFHB",
#                             TRUE ~ "NHB")) %>%
#   group_by(HOUSEID, purpose) %>%
#   summarize(n = n()) %>%
#   pivot_wider(names_from = "purpose", values_from = "n") 

```

#join trip data to hh data

```{r, message=F, echo=F, warning=F}

#carole's original category

hh_pers_trips <- left_join(sanjose_hhs, trips_by_purpose) %>%
  replace_na(list(HBW = 0,
                  HBO = 0,
                  NHB = 0)) %>%
  left_join(sanjose_pers_agg) %>%
  mutate(wfh_ratio = WFH_exh / WRKCOUNT,
         wfh_int_ = case_when(wfh_ratio == 0 ~ 'no',
                             wfh_ratio != 0 & wfh_ratio_wfh <= 0.25 ~ 'low',
                             wfh_ratio <= 0.5 & wfh_ratio > 0.25 ~ 'mid',
                             TRUE ~ 'high'))

#our version
# 
# hh_trips_Claire <- left_join(sanjose_hhs, trips_by_purpose_Claire) %>%
#   replace_na(list(HBW = 0,
#                   HBO = 0,
#                   WFHB = 0,
#                   NHB = 0))


```

#CREATE SURVEY OBJECT

```{r, message=F, echo=F, warning=F}

#carole's original category

svy_trips <- hh_pers_trips %>%
  as_survey(weights = WTHHFIN)

#our version

# svy_trips <- hh_trips_Claire %>%
#   as_survey(weights = WTHHFIN)

```

#Estimate household-level regression models

```{r, message=F, echo=F, warning=F}
HBO_model1 <- svyglm(HBO ~ zero_veh_ + size_ + inc_quint_, wfh_int_, svy_trips)

export_summs(HBO_model1, 
             error_pos = "right", 
             error_format = "(p = {p.value})",
             model.names = "Full model")

#remote non-statistically significant var (zero_veh_hh & quantile)

# HBO_model2 <- svyglm(HBO ~size_, svy_trips)
# 
# export_summs(HBO_model1, HBO_model2,
#              error_pos = "right", 
#              error_format = "(p = {p.value})",
#              model.names = c("Full model", "Reduced model"))
```

```{r, message=F, echo=F, warning=F}
HBW_model1 <- svyglm(HBW ~ zero_veh_ + size_ + inc_quint_, wfh_int_, svy_trips)

export_summs(HBW_model1, 
             error_pos = "right", 
             error_format = "(p = {p.value})",
             model.names = "Full model")

#remote non-statistically significant var (zero_veh_hh & quantile)

# HBW_model2 <- svyglm(HBW ~size_, svy_trips)
# 
# export_summs(HBW_model1, HBW_model2,
#              error_pos = "right", 
#              error_format = "(p = {p.value})",
#              model.names = c("Full model", "Reduced model"))

#Apply trip production model to zonal data
```

```{r, message=F, echo=F, warning=F}
NHB_model1 <- svyglm(NHB ~ zero_veh_ + size_ + inc_quint_, wfh_int_, svy_trips)

export_summs(NHB_model1, 
             error_pos = "right", 
             error_format = "(p = {p.value})",
             model.names = "Full model")

#remote non-statistically significant var (zero_veh_hh & quantile)

# NHB_model2 <- svyglm(NHB ~size_, svy_trips)
# 
# export_summs(NHB_model1, NHB_model2,
#              error_pos = "right", 
#              error_format = "(p = {p.value})",
#              model.names = c("Full model", "Reduced model"))

#Apply trip production model to zonal data
```

```{r, message=F, echo=F, warning=F}
## TBD
existing_zones <- here("existing",
                       "data",
                       "existing_sanjose.csv") %>%
  read_csv() %>%
  mutate(wfh_ratio = total_wfhE / total_workerE) %>%
  mutate(wfh_int = case_when(wfh_ratio >= 0 & wfh_ratio <= 0.25 ~ 'low',
                             wfh_ratio <= 0.5 & wfh_ratio > 0.25 ~ 'mid',
                             TRUE ~ 'high')) %>%
  mutate(hbo_prod = total_hhsE * HBO_model2$coefficients["(Intercept)"] +
           hh_1personE * HBO_model2$coefficients["size_one"] +
           hh_2personE * HBO_model2$coefficients["size_two"] +
           hh_3personE * HBO_model2$coefficients["size_three"])


```

```{r}
hist(existing_zones$wfh_ratio)
hist(hh_pers_trips$wfh_ratio)
```


#Trip attraction

```{r, message=F, echo=F, warning=F}

#carole's original category

existing_zones <- existing_zones %>%
  replace_na(list(basic_jobs = 0,
                  retail_jobs = 0, 
                  service_jobs = 0)) %>%
  mutate(hbo_attr = 0.7 * total_hhsE +
                    0.7 * basic_jobs +
                    8.4 * retail_jobs +
                    3.5 * service_jobs) #workers? jobs??

```

#Balancing

```{r, message=F, echo=F, warning=F}

#carole's original category

trip_end_summary <- tibble(Purpose = c("HBO"),
                           Productions = c(sum(existing_zones$hbo_prod)),
                           Attractions = c(sum(existing_zones$hbo_attr)),
                           Difference = c(sum(existing_zones$hbo_attr) - 
                                            sum(existing_zones$hbo_prod)))

kable(trip_end_summary, format.args = list(big.mark = ","))

existing_zones <- existing_zones %>%
  mutate(hbo_attr_bal = hbo_attr * 
           sum(existing_zones$hbo_prod) / sum(existing_zones$hbo_attr))

#check
trip_end_summary <- tibble(Purpose = c("HBO"),
                           Productions = c(sum(existing_zones$hbo_prod)),
                           Attractions = c(sum(existing_zones$hbo_attr_bal)),
                           Difference = c(sum(existing_zones$hbo_attr_bal) - 
                                            sum(existing_zones$hbo_prod)))

kable(trip_end_summary, format.args = list(big.mark = ","))
```

#create some chloropleth maps and/or dot-density maps

