---
title: "Assignment04"
author: "Megan Willis-Jackson, Claire Wang, Ignacio Lafuente"
date: "2/17/2022"
output: html_document
---

# Load Libraries

```{r, message=F, echo=F, warning=F}
library(sf)
library(tigris)
library(tidyverse)
library(osmdata)
library(here)
library(tidytransit)
options(java.parameters = "-Xmx5G")
library(r5r)
library(lubridate)
library(leaflet)
library(ggthemes)
library(ggspatial)
library(RColorBrewer)


```


# Download OSM data

```{r, message=F, warning=F, results='hide'}
# Load the MSA boundaries
boundary <- core_based_statistical_areas() %>% 
  filter(GEOID == "41940")

# Define a bounding box containing the MSA
sanjose_bbox <- st_bbox(boundary)

q <- opq(bbox = sanjose_bbox) %>% # create a query
  add_osm_feature(key = 'highway') %>% # request only road data
  osmdata_xml(file = 'existing/networks/streets.osm') # download osm file

```

# Zone Centroids

```{r, message=F, error=F, warning=F, results='hide'}

centroids <- here("zones",
                  "zones_sanjose.geojson") %>%
  st_read() %>%
  st_centroid() %>%
  st_transform("WGS84") %>%
  rename(id = GEOID)

st_write(centroids, here("zones", "centroids.geojson"))

zones <- here("zones",
                  "zones_sanjose.geojson") %>%
  st_read() 


ggplot(zones) +
  geom_sf() +
  geom_sf(data = centroids)

```

# Load SJ GTFS Data


```{r}
current_gtfs <- here("existing",
                     "networks",
                     "gtfs_vta.zip") %>%
  read_gtfs()


```

# Generate skims

```{r, message=F, warning=F, results='hide'}
existing_core <- here("existing",
                      "networks") %>%
  setup_r5(verbose = FALSE)

```

```{r, message=F, warning=F, results='hide'}

car_skim_existing <- travel_time_matrix(existing_core, 
                     origins = centroids,
                     destinations = centroids,
                     mode = "CAR")

walk_skim_existing <- travel_time_matrix(existing_core, 
                      origins = centroids,
                      destinations = centroids,
                      mode = "WALK")

bike_skim_existing <- travel_time_matrix(existing_core, 
                      origins = centroids,
                      destinations = centroids,
                      mode = "BICYCLE")

transit_skim_existing <- travel_time_matrix(existing_core, 
                         origins = centroids,
                         destinations = centroids,
                         mode = "TRANSIT",
                         departure_datetime = ymd_hm("2022-02-14 08:30"),
                         breakdown = TRUE)


stop_r5()


```

# Combine Files

```{r, message=F, warning=F, results='hide'}
transit_skim_existing <- transit_skim_existing %>%
  filter(n_rides > 0)

car_skim_existing <- car_skim_existing %>%
  rename(car_time = travel_time) %>%
  unique()

transit_skim_existing <- transit_skim_existing %>%
  rename(transit_time = travel_time) %>%
  unique()

walk_skim_existing <- walk_skim_existing %>%
  rename(walk_time = travel_time) %>%
  unique()

bike_skim_existing <- bike_skim_existing %>%
  rename(bike_time = travel_time) %>%
  unique()

```


# Save Existing Skims

```{r}
write_csv(bike_skim_existing, here("existing/data/bike_skim.csv"))
write_csv(walk_skim_existing, here("existing/data/walk_skim.csv"))
write_csv(transit_skim_existing, here("existing/data/transit_skim2.csv"))
write_csv(car_skim_existing, here("existing/data/car_skim.csv"))


```

# Save Alternative Skims (no change to Existing)

```{r}
write_csv(bike_skim_existing, here("alternative/data/bike_skim.csv"))
write_csv(walk_skim_existing, here("alternative/data/walk_skim.csv"))
write_csv(transit_skim_existing, here("alternative/data/transit_skim.csv"))
write_csv(car_skim_existing, here("alternative/data/car_skim.csv"))


```


# Create Isochrones

```{r, message=F, warning=F}

bike_skim_existing <- read_csv(here("existing/data/bike_skim.csv"))
walk_skim_existing <- read_csv(here("existing/data/walk_skim.csv"))
transit_skim_existing <- read_csv(here("existing/data/transit_skim2.csv"))
car_skim_existing <- read_csv(here("existing/data/car_skim.csv"))

```

The census tract with GEOID 6001441503 has the largest amount of jobs in 
the existing condition. So travel times will be calculated to this tract,
just for demonstration purposes.


```{r}
#palettes
car_map_palette <- brewer.pal(5, "YlOrBr")
transit_map_palette <- brewer.pal(5, "YlGn")
bike_map_palette <- brewer.pal(5, "BuPu")
walk_map_palette <- brewer.pal(5, "PuBu")




#car
car_mat_exist <- car_skim_existing %>%
  unique() %>%
  select(fromId, toId, car_time) %>%
  pivot_wider(names_from = toId,
              values_from = car_time) %>%
  column_to_rownames('fromId')

existing_maxjob_car <- car_mat_exist %>%
  rownames_to_column('GEOID') %>%
  select(GEOID, `06085505006`) %>%
  rename(car_existing = `06085505006`) 

zones <- zones %>%
  inner_join(existing_maxjob_car)

car_travel_map <- ggplot(zones) +
  geom_sf(aes(fill = car_existing),
          color = NA) +
  geom_sf(data = zones %>% filter(GEOID == "06085505006"), 
          fill = "magenta", color = NA) +
  scale_fill_gradientn(colours = car_map_palette, 
                       name = "Travel Time\nto Max Job Tract\nby Car") +
  annotation_scale() +
  theme_void()

#transit
transit_mat_exist <- transit_skim_existing %>%
  unique() %>%
  select(fromId, toId, transit_time) %>%
  pivot_wider(names_from = toId,
              values_from = transit_time) %>%
  column_to_rownames('fromId')

existing_maxjob_transit <- transit_mat_exist %>%
  rownames_to_column('GEOID') %>%
  select(GEOID, `06085505006`) %>%
  rename(transit_existing = `06085505006`) 

zones <- zones %>%
  left_join(existing_maxjob_transit)

transit_travel_map <- ggplot(zones) +
  geom_sf(aes(fill = transit_existing),
          color = NA) +
  geom_sf(data = zones %>% filter(GEOID == "06085505006"), 
          fill = "magenta", color = NA) +
  scale_fill_gradientn(colours = transit_map_palette, 
                       name = "Travel Time\nto Max Job Tract\nby Transit") +
  annotation_scale() +
  theme_void()

#bike
bike_mat_exist <- bike_skim_existing %>%
  unique() %>%
  select(fromId, toId, bike_time) %>%
  pivot_wider(names_from = toId,
              values_from = bike_time) %>%
  column_to_rownames('fromId')

existing_maxjob_bike <- bike_mat_exist %>%
  rownames_to_column('GEOID') %>%
  select(GEOID, `06085505006`) %>%
  rename(bike_existing = `06085505006`) 

zones <- zones %>%
  left_join(existing_maxjob_bike)

bike_travel_map <- ggplot(zones) +
  geom_sf(aes(fill = bike_existing),
          color = NA) +
  geom_sf(data = zones %>% filter(GEOID == "06085505006"), 
          fill = "magenta", color = NA) +
  scale_fill_gradientn(colours = bike_map_palette, 
                       name = "Travel Time\nto Max Job Tract\nby Bike") +
  annotation_scale() +
  theme_void()


#walk
walk_mat_exist <- walk_skim_existing %>%
  unique() %>%
  select(fromId, toId, walk_time) %>%
  pivot_wider(names_from = toId,
              values_from = walk_time) %>%
  column_to_rownames('fromId')

existing_maxjob_walk <- walk_mat_exist %>%
  rownames_to_column('GEOID') %>%
  select(GEOID, `06085505006`) %>%
  rename(walk_existing = `06085505006`) 

zones <- zones %>%
  left_join(existing_maxjob_walk)

walk_travel_map <- ggplot(zones) +
  geom_sf(aes(fill = walk_existing),
          color = NA) +
  geom_sf(data = zones %>% filter(GEOID == "06085505006"), 
          fill = "magenta", color = NA) +
  scale_fill_gradientn(colours = walk_map_palette, 
                       name = "Travel Time\nto Max Job Tract\nby Foot") +
  annotation_scale() +
  theme_void()

car_travel_map
transit_travel_map
bike_travel_map
walk_travel_map

ggsave("graphics/car_travel_map.jpeg", car_travel_map, device = "jpeg")
ggsave("graphics/transit_travel_map.jpeg", transit_travel_map, device = "jpeg")
ggsave("graphics/bike_travel_map.jpeg", bike_travel_map, device = "jpeg")
ggsave("graphics/walk_travel_map.jpeg", walk_travel_map, device = "jpeg")



```




















